config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mainapp.urls", namespace="mainapp")),
]

mainapp/urls.py
from django.urls import path

from mainapp.apps import MainappConfig
from mainapp.views import FloatFormView, CatListView, HomePage

app_name = MainappConfig.name

urlpatterns = [
    path("", HomePage.as_view(), name="home"),
    path("cat_list/", CatListView.as_view(), name="cat_list"),
    path("float_form/", FloatFormView.as_view(), name="float_form"),
]

mainapp/models.py
from django.db import models


class Session(models.Model):
    key = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class SessionUrl(models.Model):
    url = models.CharField(max_length=40)
    session_key = models.ForeignKey(Session, on_delete=models.CASCADE)

mainapp/views.py
import logging

from django.conf import settings
from django.shortcuts import redirect
from django.views.generic import ListView, TemplateView

from .models import Session, SessionUrl
from .services.cat_api import get_cat

logger = logging.getLogger(__name__)


class HomePage(TemplateView):
    """Home page"""
    template_name = "mainapp/index.html"
    context_object_name = "cats"
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        """
        Метод проверяет есть ли ключ сессии в браузере (Application - Cookie),
        если его нет, то ключ устанавливается.
        Устанавливается на какой срок действует ключ.
        Проверяется есть ли уже такой ключ, если нет то
        ключ сохраняется в таблицу Session.
        Проверяется есть ли в БД записи с url изображений котов согласно
        ключу сессии. Если есть-то редирект на cat_list/.
        Если нет-то открывается главная страница
        """
        if not request.session.session_key:
            request.session.create()
            request.session.set_expiry(settings.SESSION_COOKIE_AGE)

        sessionid = request.session.session_key

        if not Session.objects.filter(key=sessionid).exists():
            data = Session.objects.create(key=sessionid)
            data.save()

        key = Session.objects.get(key=sessionid)
        id = key.id
        if SessionUrl.objects.filter(session_key_id=id).exists():
            return redirect('cat_list/')
        else:
            return super().get(request, *args, **kwargs)


class FloatFormView(TemplateView):
    """Форма на htmx, для запроса количества котов"""

    template_name = "mainapp/float_form.html"


class CatListView(ListView):
    """Страница с котами"""

    template_name = "mainapp/cat_list.html"
    context_object_name = "cats"
    paginate_by = 2

    def get_queryset(self):
        """
        Метод проверяет есть ли uls котов в БД по ключу сесссии.
        Если есть-то отправляет в браузер content со списком url котов.
        Если нет-то запрашивает сервис API get_cat() и добавляет url в БД.
        Отправляет в браузер content со списком url котов из БД.
        """
        sessionid = self.request.session.session_key
        session = Session.objects.get(key=sessionid)
        content = []
        key = Session.objects.get(key=sessionid)
        id = key.id

        if SessionUrl.objects.filter(session_key_id=id).exists():
            urls = SessionUrl.objects.filter(session_key_id=id)
            for i in urls:
                content.append(i.url)
            return content

        else:
            cat_num = self.request.GET.get("cat_num")
            content = get_cat(cat_num)
            logger.info(f"LOG MESSAGE: {content}")
            for i in content:
                if not SessionUrl.objects.filter(session_key=session, url=i).exists():
                    url = SessionUrl(session_key=session, url=i)
                    url.save()
            return content

templates/base.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}" />
    <title>{{ main_title }}</title>
</head>
<body>
    {% include 'header.html' %}
    <div class="container d-flex justify-content-center align-items-center content">
        {% block content %}{% endblock %}
    </div>
    {% include 'footer.html' %}
</body>
<script src="https://unpkg.com/htmx.org@1.9.12"
        integrity="sha384-ujb1lZYygJmzgSwoxRggbCHcjc0rB2XoQrxeTUQyRjrOnlCoYta87iKBWq3EsdM2" crossorigin="anonymous">
</script>
</html>

templates/footer.html
<footer class="py-3 my-4 footer">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="{% url 'mainapp:home' %}" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">© 2022 Company, Inc</p>
</footer>

templates/header.html
<header>
    <div class="px-3 py-2 bg-dark text-white">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

          <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
            <li>
              <a href="{% url 'mainapp:home' %}" class="nav-link text-secondary">
                Home
              </a>
            </li>
            <li>
              <a href="#" class="nav-link text-white">
                Add more cats
              </a>
            </li>
            <li>
              <a href="{% url 'admin:index' %}" class="nav-link text-white">
                Admin
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="px-3 py-2 border-bottom mb-3">
      <div class="container d-flex flex-wrap justify-content-center">
        <form class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto">
          <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <button type="button" class="btn btn-light text-dark me-2">Login</button>
          <button type="button" class="btn btn-primary">Sign-up</button>
        </div>
      </div>
    </div>
  </header>

templates/mainapp/cat_list.html
{% extends "base.html" %}
{% block content %}

<ul class="list-unstyled" >
    {% for i in cats %}
        <div class="d-flex justify-content-center align-items-center">
            <img src="{{ i }}" alt="Cat Photo" width="240" height="160">
        </div>
        <br>
    {% endfor %}

    <!-- Pagination -->
    {% if page_obj.paginator.num_pages > 1 %}
      <nav aria-label="Page navigation example" class="d-flex justify-content-center align-items-center">

        <ul class="pagination">
            {% if page_obj.has_previous %}
              <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            {% endif %}

            {% for i in page_obj.paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}"> {{ i }} </a></li>
              {% elif i > page_obj.number|add:"-3" and i < page_obj.number|add:"3" %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}"> {{ i }} </a></li>
              {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            {% endif %}
        </ul>

      </nav>
    {% endif %}
    <!-- END Pagination -->

</ul>

{% endblock %}

templates/mainapp/float_form.html
<div class="d-flex justify-content-center align-items-center">
  <form action="{% url 'mainapp:cat_list' %}" method="get">
    {% csrf_token %}
    <label>How many cats do you want to get?</label>
    <input type="text" class="form-control" style="width: 150%;" name="cat_num">
    <br>
    <button type="submit" class="btn btn-outline-dark">Get cats!</button>
  </form>
</div>

templates/mainapp/index.html
{% extends "base.html" %}
{% block content %}

<button type="submit" class="btn btn-outline-dark" hx-trigger="mouseover"
        hx-get="/float_form" hx-swap="outerHTML">Get cats!</button>

{% endblock %}